<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Edit $block */
?>
<?php $_company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class) ?>
<?php $_telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class) ?>
<?php $_fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class) ?>
<div>Your Shipping Address is being managed by your Company. Adding a new address is not allowed.</div>
<div></div>
<?php
    // If implementing a control option for this, note that the Address Book controller handles an automatic
    // redirect from the Book to the Edit interface if no Addresses are present. See the Address Book controller at
    // magento/vendor/magento/module-customer/Controller/Address/Index.php
?>